### ISSUE TITLE
Foundry 9 Dnd5e

### ISSUE THREAD

**Issue by shecrio** [David-Zvekic/DragTransfer#10]
Baseline function still works with no issue, however holding Alt to clone items does not. Looks like in V9 they changed getkey to something else, I had the error the other day but don't see it popping up this time, however the function still does not work.

**Comment by Dick-K** [comment]
Same for Call of Cthulhu 7e (Unofficial).

**Comment by David-Zvekic** [comment]
version 1.3.0 has been updated to be compatible with Foundry 0.9.245
