### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [David-Zvekic/DragTransfer#11]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by David-Zvekic** [comment]
I don't know if DragTransfer is compatible with versions beyond the latest
version I've tested 0.9.245

**Comment by brunocalado** [comment]
Every new v9 build you have this warning.

The v9 builds are supposed to not broke anything. 

This "compatibleCoreVersion":"9" is very useful. Check out another modules. Lots of devs are using it.

**Comment by David-Zvekic** [comment]
"Every new v9 build you have this warning.

Every version of v9 newer than 0.9.245 should have a warning. That's the
purpose of the warning : to tell you that the module may not be
compatible.  I have no way to guarantee the module is compatible with
something newer than 0.9.245.

"The v9 builds are supposed to not broke anything."

Then you are saying that the warning is useless.  So you should ask Foundry
core devs to disable it.

Maybe someone can create a module compatible with ":9" which turns off the
warning so nobody needs to pay attention to the useless warning.

**Comment by farling42** [comment]
At the very least "0.9.x" should be changed to "9.x", since the "0." prefix is no longer recognised by the version matching system.

Without the leading "0." the compatibility warning will be removed when the "9.x" matches the Foundry version "9.x".

**Comment by David-Zvekic** [comment]
you are right about that.  updated to corecompatibleversion 9.249
