### ISSUE TITLE
Clone key during drop

### ISSUE THREAD

**Issue by CarnVanBeck** [David-Zvekic/DragTransfer#3]
It would be cool, if a hotkey could be defined that, when holding it while dropping an item on a sheet, temporarily disables the deletion.
Basically a hold-to-clone button.

**Comment by David-Zvekic** [comment]
good idea! I'll investigate this

**Comment by David-Zvekic** [comment]
as of version 1.2.0 holding ALT when the drag begins will disable the deletion and allow standard FoundryVTT behavior.
