### ISSUE TITLE
Holdin "ALT" key to disable doesn't work

### ISSUE THREAD

**Issue by Sravdar** [David-Zvekic/DragTransfer#4]
Trying to transfer items between 2 player actor by holding "ALT" key. It keeps deleting the old item.

Tested all modules disabled except DragTransfer in FVTT 0.8.6, DnD5e 1.3.3

**Comment by David-Zvekic** [comment]
This feature was added in 1.2.0 which was not linked to FoundryVTT.com until 30 seconds ago.  Did you install directly from GitHub or from FoundryVTT.com?
It's on on the FoundryVTT module install tool now.

I tested it with exactly that game system and version of foundry you reported so it should work.  If it doesn't then can you turn on debugger tools in your browser and tell me what it says when you try to drag? maybe your characters sheets are not the same type.

**Comment by Sravdar** [comment]
My bad. I was maintaing it from FVTT. After update it got fixed.
